export const SPANISH_MOVE_DICTIONARY: Record<string, string> = {
  "Vine Whip": "Látigo Cepa",
  "Tackle": "Placaje",
  "Sludge Bomb": "Bomba Lodo",
  "Seed Bomb": "Bomba Germen",
  "Power Whip": "Latigazo",
  "Razor Leaf": "Hoja Afilada",
  "Solar Beam": "Rayo Solar",
  "Petal Blizzard": "Tormenta de Pétalos",
  "Sludge": "Residuos",
  "Frenzy Plant": "Planta Feroz",
  "Ember": "Ascuas",
  "Scratch": "Arañazo",
  "Flame Charge": "Nitrocarga",
  "Flame Burst": "Pirotecnia",
  "Flamethrower": "Lanzallamas",
  "Fire Fang": "Colmillo Ígneo",
  "Fire Punch": "Puño Fuego",
  "Fire Spin": "Giro Fuego",
  "Air Slash": "Tajo Aéreo",
  "Wing Attack": "Ataque Ala",
  "Dragon Breath": "Dragoaliento",
  "Fire Blast": "Llamarada",
  "Dragon Claw": "Garra Dragón",
  "Overheat": "Sofoco",
  "Air Cutter": "Air Cutter",
  "Blast Burn": "Anillo de Fuego",
  "Bubble": "Burbuja",
  "Aqua Jet": "Acua Jet",
  "Aqua Tail": "Aqua Tail",
  "Water Pulse": "Pulsar Agua",
  "Water Gun": "Pistola Agua",
  "Bite": "Mordisco",
  "Ice Beam": "Rayo Hielo",
  "Hydro Pump": "Hidrobomba",
  "Rollout": "Rollout",
  "Flash Cannon": "Foco Resplandor",
  "Skull Bash": "Cabezazo",
  "Hydro Cannon": "Hidrocañón",
  "Bug Bite": "Picadura",
  "Struggle": "Struggle",
  "Struggle Bug": "Acoso",
  "Confusion": "Confusión",
  "Bug Buzz": "Bug Buzz",
  "Psychic": "Psíquico",
  "Signal Beam": "Doble Rayo",
  "Poison Sting": "Picotazo Veneno",
  "Infestation": "Infestation",
  "Poison Jab": "Puya Nociva",
  "Aerial Ace": "Aerial Ace",
  "X Scissor": "X Scissor",
  "Fell Stinger": "Aguijón Letal",
  "Drill Run": "Taladradora",
  "Quick Attack": "Ataque Rápido",
  "Twister": "Ciclón",
  "Steel Wing": "Steel Wing",
  "Gust": "Tornado",
  "Hurricane": "Vendaval",
  "Brave Bird": "Pájaro Osado",
  "Feather Dance": "Feather Dance",
  "Dig": "Excavar",
  "Hyper Fang": "Hiperdiente",
  "Body Slam": "Body Slam",
  "Hyper Beam": "Hiperrayo",
  "Peck": "Picotazo",
  "Drill Peck": "Pico Taladro",
  "Sky Attack": "Ataque Aéreo",
  "Fly": "Vuelo",
  "Acid": "Ácido",
  "Wrap": "Wrap",
  "Poison Fang": "Colmillo Veneno",
  "Gunk Shot": "Gunk Shot",
  "Dragon Tail": "Cola Dragón",
  "Dark Pulse": "Pulso Umbrío",
  "Sludge Wave": "Onda Tóxica",
  "Acid Spray": "Acid Spray",
  "Thunder Shock": "Impactrueno",
  "Present": "Present",
  "Discharge": "Chispazo",
  "Thunderbolt": "Rayo",
  "Wild Charge": "Voltio Cruel",
  "Surf": "Surf",
  "Thunder": "Trueno",
  "Volt Switch": "Voltiocambio",
  "Spark": "Chispa",
  "Charm": "Encanto",
  "Brick Break": "Demolición",
  "Thunder Punch": "Puño Trueno",
  "Trailblaze": "Trailblaze",
  "Counter": "Contraataque",
  "Focus Blast": "Focus Blast",
  "Mud Shot": "Disparo Lodo",
  "Rock Slide": "Avalancha",
  "Sand Tomb": "Sand Tomb",
  "Rock Tomb": "Tumba de Rocas",
  "Metal Claw": "Garra Metal",
  "Earthquake": "Terremoto",
  "Bulldoze": "Bulldoze",
  "Scorching Sands": "Scorching Sands",
  "Night Slash": "Tajo Umbrío",
  "Mud Slap": "Mud Slap",
  "Stone Edge": "Roca Afilada",
  "Earth Power": "Tierra Viva",
  "Horn Attack": "Horn Attack",
  "Iron Tail": "Iron Tail",
  "Double Kick": "Double Kick",
  "Fury Cutter": "Fury Cutter",
  "Megahorn": "Megahorn",
  "Pound": "Pound",
  "Zen Headbutt": "Zen Headbutt",
  "Disarming Voice": "Voz Cautivadora",
  "Moonblast": "Fuerza Lunar",
  "Swift": "Swift",
  "Charge Beam": "Charge Beam",
  "Fairy Wind": "Fairy Wind",
  "Dazzling Gleam": "Brillo Mágico",
  "Meteor Mash": "Puño Meteoro",
  "Draining Kiss": "Beso Drenaje",
  "Weather Ball Fire": "Weather Ball Fire",
  "Feint Attack": "Finta",
  "Heat Wave": "Heat Wave",
  "Psyshock": "Psicocarga",
  "Gyro Ball": "Gyro Ball",
  "Play Rough": "Carantoña",
  "Icy Wind": "Icy Wind",
  "Shadow Ball": "Bola Sombra",
  "Ominous Wind": "Viento Aciago",
  "Cross Poison": "Cross Poison",
  "Psybeam": "Psicorrayo",
  "Silver Wind": "Silver Wind",
  "Mud Bomb": "Bomba Fango",
  "Sucker Punch": "Sucker Punch",
  "Foul Play": "Juego Sucio",
  "Power Gem": "Power Gem",
  "Payback": "Payback",
  "Cross Chop": "Tajo Cruzado",
  "Bubble Beam": "Bubble Beam",
  "Synchronoise": "Synchronoise",
  "Liquidation": "Liquidation",
  "Karate Chop": "Golpe Kárate",
  "Low Sweep": "Puntapié",
  "Low Kick": "Low Kick",
  "Close Combat": "Abocajarro",
  "Ice Punch": "Puño Hielo",
  "Rage Fist": "Rage Fist",
  "Flame Wheel": "Flame Wheel",
  "Snarl": "Alarido",
  "Thunder Fang": "Thunder Fang",
  "Crunch": "Triturar",
  "Psychic Fangs": "Psychic Fangs",
  "Scald": "Scald",
  "Rock Smash": "Golpe Roca",
  "Dynamic Punch": "Puño Dinámico",
  "Power Up Punch": "Power Up Punch",
  "Submission": "Sumisión",
  "Psycho Cut": "Psicocorte",
  "Futuresight": "Futuresight",
  "Bullet Punch": "Puño Bala",
  "Heavy Slam": "Cuerpo Pesado",
  "Bullet Seed": "Bullet Seed",
  "Magical Leaf": "Magical Leaf",
  "Leaf Blade": "Leaf Blade",
  "Leaf Tornado": "Leaf Tornado",
  "Blizzard": "Ventisca",
  "Rock Throw": "Lanzarocas",
  "Rock Blast": "Rock Blast",
  "Ancient Power": "Poder Pasado",
  "Stomp": "Stomp",
  "Incinerate": "Incinerate",
  "Drain Punch": "Drain Punch",
  "Magnet Bomb": "Bomba Imán",
  "Zap Cannon": "Zap Cannon",
  "Cut": "Cut",
  "Ice Shard": "Ice Shard",
  "Lick": "Lengüetazo",
  "Aurora Beam": "Aurora Beam",
  "Frost Breath": "Vaho Gélido",
  "Razor Shell": "Razor Shell",
  "Avalanche": "Alud",
  "Astonish": "Impresionar",
  "Night Shade": "Night Shade",
  "Shadow Claw": "Garra Umbría",
  "Shadow Punch": "Puño Sombra",
  "Hex": "Infortunio",
  "Breaking Swipe": "Breaking Swipe",
  "Iron Head": "Cabeza de Hierro",
  "Vice Grip": "Vice Grip",
  "Crabhammer": "Crabhammer",
  "Extrasensory": "Extrasensory",
  "Bone Club": "Bone Club",
  "Blaze Kick": "Blaze Kick",
  "Grass Knot": "Grass Knot",
  "Outrage": "Enfado",
  "Dragon Pulse": "Pulsadragón",
  "Waterfall": "Cascada",
  "Hidden Power": "Hidden Power",
  "Super Power": "Fuerza Bruta",
  "Splash": "Splash",
  "Sparkling Aria": "Sparkling Aria",
  "Transform": "Transform",
  "Last Resort": "Last Resort",
  "Brine": "Brine",
  "Yawn": "Yawn",
  "Triple Axel": "Triple Axel",
  "Draco Meteor": "Cometa Draco",
  "Psystrike": "Onda Mental",
  "Energy Ball": "Energy Ball",
  "Ice Fang": "Colmillo Hielo",
  "Shadow Sneak": "Sombra Vil",
  "Lunge": "Plancha",
  "Brutal Swing": "Brutal Swing",
  "Meteor Beam": "Meteor Beam",
  "Weather Ball Water": "Weather Ball Water",
  "Acrobatics": "Acrobatics",
  "Leaf Storm": "Leaf Storm",
  "Mirror Coat": "Mirror Coat",
  "Mirror Shot": "Mirror Shot",
  "Upper Hand": "Upper Hand",
  "Powder Snow": "Nieve Polvo",
  "High Horsepower": "High Horsepower",
  "Icicle Spear": "Icicle Spear",
  "Lock On": "Lock On",
  "Octazooka": "Octazooka",
  "Tri Attack": "Tri Attack",
  "Placaje (Tackle)": "Placaje (Tackle)",
  "Hiperrayo (Hyper Beam)": "Hiperrayo (Hyper Beam)",
  "Aura Sphere": "Esfera Aural",
  "Smack Down": "Lanzarocas",
  "Aeroblast": "Aeroblast",
  "Sacred Fire": "Sacred Fire",
  "Muddy Water": "Muddy Water",
  "Force Palm": "Force Palm",
  "Boomburst": "Boomburst",
  "Weather Ball Rock": "Weather Ball Rock",
  "Weather Ball Normal": "Weather Ball Normal",
  "Poltergeist": "Poltergeist",
  "Take Down": "Take Down",
  "Mist Ball": "Mist Ball",
  "Luster Purge": "Luster Purge",
  "Origin Pulse": "Pulso Primigenio",
  "Precipice Blades": "Filo del Abismo",
  "Doom Desire": "Doom Desire",
  "Psycho Boost": "Psycho Boost",
  "Leafage": "Leafage",
  "Weather Ball Ice": "Weather Ball Ice",
  "Rock Wrecker": "Rock Wrecker",
  "Roar of Time": "Distorsión",
  "Spacial Rend": "Corte Vacío",
  "Magma Storm": "Lluvia Ígnea",
  "Giga Impact": "Giga Impact",
  "Crush Grip": "Crush Grip",
  "Shadow Force": "Shadow Force",
  "Seed Flare": "Seed Flare",
  "V Create": "V Create",
  "Water Shuriken": "Water Shuriken",
  "High Jump Kick": "High Jump Kick",
  "Sacred Sword": "Espada Santa",
  "Fusion Flare": "Llama Fusión",
  "Fusion Bolt": "Rayo Fusión",
  "Glaciate": "Mundo Gélido",
  "Techno Blast Normal": "Techno Blast Normal",
  "Chilling Water": "Chilling Water",
  "Parabolic Charge": "Parabolic Charge",
  "Flying Press": "Flying Press",
  "Geomancy": "Geomancy",
  "Oblivion Wing": "Ala Mortífera",
  "Spirit Shackle": "Spirit Shackle",
  "Darkest Lariat": "Darkest Lariat",
  "Clanging Scales": "Clanging Scales",
  "Natures Madness": "Natures Madness",
  "Sunsteel Strike": "Meteoro Impacto",
  "Moongeist Beam": "Rayo Umbrío",
  "Double Iron Bash": "Double Iron Bash",
  "Obstruct": "Obstruct",
  "Aura Wheel Electric": "Aura Wheel Electric",
  "Behemoth Blade": "Espada Suprema",
  "Behemoth Bash": "Escudo Supremo",
  "Dynamax Cannon": "Cañón Dinamax",
  "Thunder Cage": "Jaula Trueno",
  "Dragon Energy": "Dragoenergía",
  "Flower Trick": "Truco Floral",
  "Torch Song": "Canto Ardiente",
  "Aqua Step": "Danza Acuática"
};

export function getSpanishMoveName(englishMoveName: string): string {
  if (!englishMoveName) return '';
  const trimmed = englishMoveName.trim();
  if (SPANISH_MOVE_DICTIONARY[trimmed]) {
    return SPANISH_MOVE_DICTIONARY[trimmed];
  }

  // Handle combined move strings like "Behemoth Blade / Play Rough" or "Close Combat, Play Rough"
  if (trimmed.includes('/') || trimmed.includes(',') || /\s+y\s+/i.test(trimmed) || /\s+and\s+/i.test(trimmed)) {
    const parts = trimmed.split(/[\/,]|\s+y\s+|\s+and\s+/i).map((s) => s.trim()).filter(Boolean);
    return parts.map((p) => SPANISH_MOVE_DICTIONARY[p] || p).join(' / ');
  }

  return trimmed;
}

export function getTranslatedMoveName(englishMoveName: string, lang?: string): string {
  return getSpanishMoveName(englishMoveName);
}
